### ISSUE TITLE
awesome example - authentication needed

### ISSUE THREAD

**Issue by mihai-satmarean** [vfarcic/monitoring#1]
Hi,
I find the example very good and I am trying to figure out how to add authentication.
I have seen the nginx reverse proxy idea,
but honestly I am not that experienced to make a container that can do that and plug it in the current configuration.
Any chance that you would add this functionality?
Thanks!

**Comment by vfarcic** [comment]
I'd appreciate a bit more info in order to try come up with the best solution. Can you tell me what type of authentication you're trying to implement? Should it be applied for the whole server (cluster), only for the access to logs, db...? If you can let me know what you're trying to protect I can get back to you with the idea and probably short instructions.

**Comment by mihai-satmarean** [comment]
I will try to explain:
The purpose is to be able to expose the whole working stack to Internet.
But Elasticsearch is not secure, Kibana is not secure and some other ports
are opened there.
Since the ELK does not have its own user management
I was trying to adapt (as seen in another examples) an nginx docker image
to act as a proxy for the ELK  and provide basic HTTP authentication. Which
seemed doable even for a novice but ..
But I am still not there as I am trying to use Ansible for everything, it
gets complex when I want to add a new container that interferes with the
other containers.

I hope this makes more clear what I intend to do.
It would be great to get some help on this topics,
Thanks!

PS.
We liked all your articles on Continuous _everything_ and we try to
implement the concepts in our infrastructure

2015-09-02 22:01 GMT+02:00 Viktor Farcic notifications@github.com:

**Comment by vfarcic** [comment]
In most cases I'm exposing only ports 80 (HTTP) and 443 (HTTPS) to internet. All the rest is behind the corporate firewalls and accessible only through the internal network.

If you need a very small number of users, you can do it with nginx: http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html. However, I advise you to do it like that only if you need to give access to specific people operating outside of the local network. More elaborated example would be to, for example, use OAuth2 but that would require you to take some third party services or develop your own. Later option is relatively simple and almost any programming language has at least one OAuth library.

I'm not sure if I answered your question. Please let me know if you need more info or give me a call on HangOuts and we can chat.

You said that things get complex with Ansible and a lot of containers. Did you try Swarm? It simplifies deployments and scaling a lot.

P.S. You're located in Germany?

**Comment by mihai-satmarean** [comment]
The case is only for some people outside the network.
RIght now I am using Kibana 3 (from jar) and an Apache proxy which does the
job. But we want to kill the server completely in the future.
Actually the design I have seen, would be that an nginx container would do
the proxy for all the other 3 from ELK or any other services.
It has an easy way to add or remove routes.

If you have time please have a look here
https://github.com/jwilder/nginx-proxy

I did not had the time to make a mockup, but next week I will do. I guess
it would work ok but let see.

We want to move to containers because of the flexibility and deployment
options and so on.

I did not used swarm as we are not that into containers yet, but definitely
I will have  a look.

On another project I would want to use this ELK setup too, we want to use
ansible to kind of take over on the legacy infrastructure and change as we
go with ansible controlled and managed infrastructure.

PS.
Yes I am located in Germany.
For hangout I could not make it this week, too many things happening,  if
you are in my timezone I will try to contact you, if not, maybe we find a
timewindow.

Thanks a lot.

2015-09-03 18:31 GMT+02:00 Viktor Farcic notifications@github.com:
