### ISSUE TITLE
Errors during Vagrant up

### ISSUE THREAD

**Issue by ghost** [vfarcic/monitoring#3]
Hi, and first of all thanks for the great articles!

I have successfully used this stack before, but when I try to run "vagrant up" now, I run into some problem:

==> elk: Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-ggSmyq-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cryptography
==> elk: Storing debug log for failure in /root/.pip/pip.log
==> elk: Running provisioner: shell...
    elk: Running: inline script
==> elk: stdin: is not a tty
==> elk: Traceback (most recent call last):
==> elk:   File "/usr/local/bin/ansible-playbook", line 44, in <module>
==> elk:     import ansible.playbook
==> elk:   File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/**init**.py", line 20, in <module>
==> elk:     import ansible.runner
==> elk:   File "/usr/local/lib/python2.7/dist-packages/ansible/runner/**init**.py", line 32, in <module>
==> elk:     import jinja2
==> elk:   File "/usr/local/lib/python2.7/dist-packages/jinja2/**init**.py", line 33, in <module>
==> elk:     from jinja2.environment import Environment, Template
==> elk:   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 13, in <module>
==> elk:     from jinja2 import nodes
==> elk:   File "/usr/local/lib/python2.7/dist-packages/jinja2/nodes.py", line 19, in <module>
==> elk:     from jinja2.utils import Markup
==> elk:   File "/usr/local/lib/python2.7/dist-packages/jinja2/utils.py", line 531, in <module>
==> elk:     from markupsafe import Markup, escape, soft_unicode
==> elk: ImportError: No module named markupsafe
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Most likely relates to commands executed in ansible.sh:
sudo apt-get install -y python-pip python-dev
sudo pip install ansible==1.9.2

Is this something you have experienced before, or can you guide me towards a solution?

**Comment by vfarcic** [comment]
That's a very old repo. I haven't used it in a long time... A lot of things changed in the meantime.

I updated a few things (Docker setup, LogStash configuration, Ansible, ...). Can you please try it out and let me know whether it works?

**Comment by ghost** [comment]
Hi, sorry for the late response..

It is indeed a old repo, which caused me to actually create my own repo for a configurable swarm cluster using vagrant + ansible based on docker 1.12+(https://github.com/Uncharted89/swarm-base-ansible). I have also seen that you have some example of the elk stack in your more active repos.

This repo seems to work now though. Thank you for your time.

And also, thank you for the devops-toolkit book! It's amazing. Highly recommending it to collegues etc..
